name: "Update"

on:
  schedule:
    - cron: '8 */4 * * *' # At minute 8 past every 4th hour
  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install WHOIS client
        run: sudo apt install -y whois parallel gawk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('utils/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          pip install -r utils/requirements.txt

      - name: Download IPs
        run: |
          set -euo pipefail
          set -x
          find . -name downloader.sh | sort -h | awk '{print "Executing "$1"...";system("bash "$1)}'

      - name: Merge ipv4 Ranges
        run: |
          set -euo pipefail
          set -x
          find . -name ipv4.txt | sort -h | parallel --will-cite -j 1 echo "Merging '{}'"';'python utils/merge.py --source={} '|'  sort -V '>' {.}_merged.txt

      - name: Merge ipv6 Ranges
        run: |
          set -euo pipefail
          set -x
          find . -name ipv6.txt | sort -h | parallel --will-cite -j 1 echo "Merging '{}'"';'python utils/merge.py --source={} '|' sort -V '>' {.}_merged.txt

      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[auto] Update IP ranges"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          push_options: "--force-with-lease"
          branch: ${{ github.ref_name }}
